# Site settings
title: Analysis of Global and Regional Remittance Flow
author: Jane Luke and Bukola Anifowoshe
name: Jane Luke
email: janeluke0@gmail.com
description: "A 2022 Project for CYPLAN 255 at the University of California, Berkeley"
github_username: janeluke

# Build settings
remote_theme: jekyll/minima

theme: jekyll-theme-slate
