# Site settings
title: Final Project May Finally Work
author:
name: Jane Luke
email: janeluke0@gmail.com
description: "Please work please"
github_username: janeluke

# Build settings
remote_theme: jekyll/minima
